In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3], [4, 5, 6]])
Y = np.array([[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]])

In [3]:
X.sum()

np.int64(21)

In [4]:
Y

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [5]:
X**Y

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
X**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [8]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [9]:
import sys
sys.path.append("./python")
import numpy as np
import needle as ndl

ModuleNotFoundError: No module named 'needle'

In [ ]:
a = ndl.Tensor([[1, 2, 3], [4, 5, 6]])
b = a.transpose((1, 0))
b.sum()

NotImplementedError: 

In [ ]:
a = 1
b = 2
a != b

True

In [ ]:
a = (1, 2)
b = (0, 2)
a < b

False

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]]).T
C = np.dot(A, B)
C

array([[ 50,  68],
       [122, 167]])

In [18]:
B

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [19]:
x = np.random.randn(6, 6, 5, 4)
y = np.random.randn(6, 6, 4, 3)
x @ y

array([[[[-3.36867473e+00,  9.33807826e-01, -3.25532871e+00],
         [ 5.98650617e-01, -7.64522064e-01,  8.44410337e-01],
         [ 1.60527827e+00, -2.97385767e-01,  2.89143390e+00],
         [ 3.93320679e-01, -2.90047004e+00,  6.41996485e-02],
         [-1.83051314e+00,  3.24273154e-01,  5.65561057e-01]],

        [[ 4.71964538e-01, -2.32431978e+00, -1.56447624e+00],
         [-2.23199952e+00,  1.07511830e+00,  3.96024676e-01],
         [ 6.76586092e-01, -8.10675345e-01,  1.99055443e-02],
         [-1.44166613e+00,  6.57525320e+00, -8.98602431e-01],
         [ 1.40852447e+00, -9.69744454e-01, -1.42957492e+00]],

        [[-1.34489444e+00, -6.41485335e-01,  7.89403214e-01],
         [ 1.91894320e+00, -8.06248984e-01,  1.45580706e+00],
         [-2.13855476e+00,  1.72595049e+00, -9.95388202e-01],
         [ 3.65719084e+00, -8.01940539e-01,  3.97163391e-01],
         [-5.40456854e-01,  9.30256912e-01,  3.07690104e-01]],

        [[ 1.31878647e+00,  5.36912033e-01,  3.50872186e-01],
  

In [1]:
import sys
sys.path.append("./hw1/python")
sys.path.append('./apps')
import numpy as np

In [2]:
import needle as ndl

a = ndl.Tensor(np.random.randn(3, 4))


In [3]:
a

needle.Tensor([[-1.45099616  1.08444558 -1.69657712  1.45923739]
 [-0.74413876  0.92077965 -0.54449605 -1.16241245]
 [-0.87506727 -0.92918977  0.81698633 -2.25130553]])

In [4]:
ndl.relu(a)

needle.Tensor([[0.         1.08444558 0.         1.45923739]
 [0.         0.92077965 0.         0.        ]
 [0.         0.         0.81698633 0.        ]])

In [5]:
a

needle.Tensor([[-1.45099616  1.08444558 -1.69657712  1.45923739]
 [-0.74413876  0.92077965 -0.54449605 -1.16241245]
 [-0.87506727 -0.92918977  0.81698633 -2.25130553]])

In [6]:
b = ndl.relu(a)
b

needle.Tensor([[0.         1.08444558 0.         1.45923739]
 [0.         0.92077965 0.         0.        ]
 [0.         0.         0.81698633 0.        ]])

In [10]:
out_grad = ndl.Tensor([[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]], dtype="float32")

In [11]:
out_grad

needle.Tensor([[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]])

In [12]:
b.op.gradient_as_tuple(out_grad, b)

(needle.Tensor([[0. 1. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]),)

In [13]:
l = ndl.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])

In [15]:
b = l.sum((1,))
b

needle.Tensor([10 26 42 58 74])